### PR TITLE
better error reporting

### PR DESCRIPTION
**Pull request by sonoro1234**

### CODE REVIEW

**Comment by sonoro1234** [comment]
@ColonelThirtyTwo 
Most important change is to allow having an init phase in the callback
```lua
function initcallback()
    --doing initialization
    local ffi = require"ffi"
    return function(a,b,c)
        -- here is the real callback
        print(a)
        ...
    end
end
```
I am using it in https://github.com/sonoro1234/LuaJIT-SDL2
But what I would really like is having args in initcallback (a mutex for example) althought I still dont know how to do it, mainly because I should use lua_pushsomething but something could be anything.

**Comment by ColonelThirtyTwo** [comment]
Hi @sonoro1234 
Thank you for your interest in my code! I'm not maintaining my Lua code anymore, so I recommend you fork the project if you want to work on it.

**Comment by sonoro1234** [comment]
Thank you
Did you lost interest in LuaJIT?

**Comment by ColonelThirtyTwo** [comment]
@sonoro1234 For the most part, yes. It's still a good option IMO for embedding a scripting language into other things, but for the type of work I'm doing there are better options.

**Pull request closed without merging**
